### ISSUE TITLE
Server Proxy not being properly called

### ISSUE THREAD

**Issue by Starisho** [codycoolwaffle/Sky_Tinkering#2]
I was trying to put this mod into a server I am making for personal use, and the server crashes due to this mod having/causing an error. I cannot find configs for this mod either. It works perfectly well in singleplayer however.

A log from the server console can be found here.

[New Text Document (7).txt](https://github.com/codycoolwaffle/Sky_Tinkering/files/1451364/New.Text.Document.7.txt)

**Comment by codycoolwaffle** [comment]
This'll be an easy fix. I'll get right on it when I get back to my computer.

**Comment by Starisho** [comment]
Awesome! Thank you!
