### ISSUE TITLE
[BUG] exCrook & IguanaTinkerTweaks Progression

### ISSUE THREAD

**Issue by spannerman79** [codycoolwaffle/Sky_Tinkering#3]
It seems that the exCrook doesn't level up compared to exHammer when using IguanaTinkerTweaks

It may be that I am missing a config setting/option in IguanaTinkerTweaks but I have looked in its config file to see if I can add a tool - seems that I can only blacklist/exclude tools.

**Comment by codycoolwaffle** [comment]
Forgot to include `public static Block[] getBlocks()` in SkyCrook. Easy fix.

**Comment by codycoolwaffle** [comment]
Well. Somehow I made it worse. Now the exHammer doesn't get xp. Yay.

**Comment by codycoolwaffle** [comment]
Fixed the exHammer, but some investigation shows the scythe doesn't gain xp from breaking leaves...

Leaves may be blocked from making xp...       oh no

**Comment by codycoolwaffle** [comment]
Found a workaround. Everything seems to be working again. Next commit will close this.
